services:
  backend:
    build: ./isl-glove-AI
    container_name: isl-backend
    networks:
      - isl-network
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017/isl_glove
      - RABBIT_MQ=amqp://guest:guest@rabbitmq:5672
      - QUEUE_NAME=letter_queue
      - NODE_ENV=development
      - MODEL_PATH=ml/model.tflite
      - PYTHON_PATH=python
    volumes:
      - ./isl-glove-AI:/app
    stdin_open: true
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  isl-network:
    external: true